### ISSUE TITLE
Do I have to install/configure anything external to make sqlite output work?

### ISSUE THREAD

**Issue by jaitor1** [wavded/ogr2ogr#37]
Hi,

Do I have to install/configure anything external to make sqlite output work?

I can make it work properly for SHP but when I change the output format to sqlite I am getting:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ERROR 6: Read or update mode not supported on /vsistdout
ERROR 4: sqlite3_open(/vsistdout/) failed: unable to open database file
SQLite driver failed to create /vsistdout/

    at ChildProcess.<anonymous> (C:\node\ogr2ogr\node_modules\ogr2ogr\index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

My code:

```
var ogr = ogr2ogr('PG:dbname=xxxx host=xxxx port=xxxx user=xxxx password=xxxx tables=test')
                    .format('SQLite')
                    .options(['-nln', 'test'])
                    .skipfailures()
                    .stream()
    ogr.pipe(fs.createWriteStream('C:/Users/jaitor1/Desktop/test.sqlite'))
```

**Comment by wavded** [comment]
Hmm, I have never worked with that format so I'm not sure. Can you get it to work with the command line `ogr2ogr` tool in the GDAL suite? If so, it's very likely we can get it to work in this project.

**Comment by saalvarem** [comment]
Hi @jaitor1,

The code you have there will work when converting to "ESRI Shapefile" because you can stream the output into a shapefile; but if you want to write to a database output like SQLite, you'll need to use the `.destination(str)` option to have ogr2ogr write to your output directly.

Your code would then look something like this:
`var ogr = ogr2ogr('PG:dbname=xxxx host=xxxx port=xxxx user=xxxx password=xxxx tables=test')
    .format('SQLite')
    .options(['-nln', 'test'])
    .skipfailures()
    .destination('C:/Users/jaitor1/Desktop/test.sqlite')
    .stream()`

Also, please note that this will produce a SQLite file (which is what you want), but if you wanted to produce a Spatialite file instead, you'd also need to pass in `["-dsco", "SPATIALITE=YES"]` to your options array, just FYI.

For more information, see:
https://www.npmjs.com/package/ogr2ogr - the part about `.destination(str)`, and
https://github.com/wavded/ogr2ogr/issues/37

Hope this helps.
Saul

**Comment by wavded** [comment]
Closing due to age, reopen if issue persists.
